//raimat aobjectand array Assignment


document.getElementById("th").innerHTML = "DATA!!!!!"
    document.getElementById("th1").innerHTML = "Workers"


    document.getElementById("t1").innerHTML = "No"
    document.getElementById("t2").innerHTML = "FirstName"
    document.getElementById("t3").innerHTML = "LastName"
    document.getElementById("t4").innerHTML = "Age"
    document.getElementById("t5").innerHTML = "Sex"
    document.getElementById("t6").innerHTML = "Position"
    document.getElementById("t7").innerHTML = "Date_of_Employment"

    document.getElementById("td11").innerHTML = "1."
    document.getElementById("td12").innerHTML = "Thompson"
    document.getElementById("td13").innerHTML = "Anthony"
    document.getElementById("td14").innerHTML = "32"
    document.getElementById("td15").innerHTML = "Male"
    document.getElementById("td16").innerHTML = "Head of Finance Department"
    document.getElementById("td17").innerHTML = "17/07/2014"

    document.getElementById("td21").innerHTML = "2."
    document.getElementById("td22").innerHTML = "Johnson"
    document.getElementById("td23").innerHTML = "Mary"
    document.getElementById("td24").innerHTML = "23"
    document.getElementById("td25").innerHTML = "Female"
    document.getElementById("td26").innerHTML = "Software Engineer"
    document.getElementById("td27").innerHTML = "05/03/2019"

    document.getElementById("td31").innerHTML = "3."
    document.getElementById("td32").innerHTML = "Chisom"
    document.getElementById("td33").innerHTML = "Onyeka"
    document.getElementById("td34").innerHTML = "28"
    document.getElementById("td35").innerHTML = "Female"
    document.getElementById("td36").innerHTML = "Human Resources Manager"
    document.getElementById("td37").innerHTML = "21/06/2016"

    document.getElementById("td41").innerHTML = "4."
    document.getElementById("td42").innerHTML = "Jide"
    document.getElementById("td43").innerHTML = "Olabisi"
    document.getElementById("td44").innerHTML = "28"
    document.getElementById("td45").innerHTML = "Male"
    document.getElementById("td46").innerHTML = "Assistant Head (Software Department)"
    document.getElementById("td47").innerHTML = "05/06/2016"

    document.getElementById("td51").innerHTML = "5."
    document.getElementById("td52").innerHTML = "Williams"
    document.getElementById("td53").innerHTML = "Ajayi"
    document.getElementById("td54").innerHTML = "30"
    document.getElementById("td55").innerHTML = "Male"
    document.getElementById("td56").innerHTML = "Head of Software Department"
    document.getElementById("td57").innerHTML = "06/09/2015"

    document.getElementById("td61").innerHTML = "6."
    document.getElementById("td62").innerHTML = "Nancy"
    document.getElementById("td63").innerHTML = "Chukwuemeka"
    document.getElementById("td64").innerHTML = "27"
    document.getElementById("td65").innerHTML = "Female"
    document.getElementById("td66").innerHTML = "Secretary"
    document.getElementById("td67").innerHTML = "23/08/2016"

    document.getElementById("td71").innerHTML = "7."
    document.getElementById("td72").innerHTML = "Nicholas"
    document.getElementById("td73").innerHTML = "Uchemba"
    document.getElementById("td74").innerHTML = "26"
    document.getElementById("td75").innerHTML = "Male"
    document.getElementById("td76").innerHTML = "Software Engineer"
    document.getElementById("td77").innerHTML = "22/02/2020"

    document.getElementById("td81").innerHTML = "8."
    document.getElementById("td82").innerHTML = "Ahmed"
    document.getElementById("td83").innerHTML = "Olayinka"
    document.getElementById("td84").innerHTML = "24"
    document.getElementById("td85").innerHTML = "Male"
    document.getElementById("td86").innerHTML = "Graphic Designer"
    document.getElementById("td87").innerHTML = "15/08/2020"

    document.getElementById("td91").innerHTML = "9."
    document.getElementById("td92").innerHTML = "Halima"
    document.getElementById("td93").innerHTML = "Mohammad"
    document.getElementById("td94").innerHTML = "26"
    document.getElementById("td95").innerHTML = "Female"
    document.getElementById("td96").innerHTML = "Senior Finance Manager"
    document.getElementById("td97").innerHTML = "30/05/2018"

    document.getElementById("td01").innerHTML = "10."
    document.getElementById("td02").innerHTML = "Richard"
    document.getElementById("td03").innerHTML = "Adeyemi"
    document.getElementById("td04").innerHTML = "41"
    document.getElementById("td05").innerHTML = "Male"
    document.getElementById("td06").innerHTML = "C.E.O"
    document.getElementById("td07").innerHTML = "17/11/2010"